USER_RESPONSE = [{
    'awaiting_feedback_count': 0,
    'creation_tsz': 1356283364,
    'feedback_info': {'count': 0, 'score': None},
    'login_name': 'mlaszuk',
    'referred_by_user_id': None,
    'user_id': 28651835,
    'user_pub_key': None
}]

SHOPS_RESPONSE = [{
    'accepts_custom_requests': False,
    'announcement': 'This is for testing only.  Nothing is actually for sale',
    'creation_tsz': 1449598530,
    'currency_code': 'USD',
    'digital_listing_count': 0,
    'digital_sale_message': 'This is for testing only.  Nothing is actually for sale',
    'has_onboarded_structured_policies': False,
    'has_unstructured_policies': True,
    'icon_url_fullxfull': None,
    'image_url_760x100': None,
    'is_using_structured_policies': False,
    'is_vacation': False,
    'languages': ['en-US'],
    'last_updated_tsz': 1449598622,
    'listing_active_count': 0,
    'login_name': 'mlaszuk',
    'num_favorers': 1,
    'policy_additional': 'This is for testing only.  Nothing is actually for sale',
    'policy_has_private_receipt_info': True,
    'policy_payment': 'This is for testing only.  Nothing is actually for sale',
    'policy_refunds': 'This is for testing only.  Nothing is actually for sale',
    'policy_seller_info': 'This is for testing only.  Nothing is actually for sale',
    'policy_shipping': 'This is for testing only.  Nothing is actually for sale',
    'policy_updated_tsz': 1449598594,
    'policy_welcome': 'This is for testing only.  Nothing is actually for sale',
    'sale_message': 'This is for testing only.  Nothing is actually for sale',
    'shop_id': 12153339,
    'shop_name': 'scarvesforrobots',
    'title': None,
    'upcoming_local_event_id': None,
    'url': 'https://www.etsy.com/shop/scarvesforrobots?utm_source=r2data21&utm_medium=api&utm_campaign=api',
    'user_id': 28651835,
    'vacation_autoreply': None,
    'vacation_message': None
}]


TRANSACTIONS_RESPONSE = [{
    'buyer_feedback_id': None,
    'buyer_user_id': 77713718,
    'creation_tsz': 1449600584,
    'currency_code': 'USD',
    'description': 'This is for testing only.  Nothing is actually for sale',
    'file_data': u'',
    'image_listing_id': 885407022,
    'is_digital': False,
    'is_quick_sale': False,
    'listing_id': 259848284,
    'materials': [],
    'paid_tsz': 1449600660,
    'price': '0.20',
    'quantity': 3,
    'receipt_id': 1062792031,
    'seller_feedback_id': None,
    'seller_user_id': 28651835,
    'shipped_tsz': None,
    'shipping_cost': '0.00',
    'tags': ['Accessories', 'Scarf', 'notforsale', 'testingonly'],
    'title': 'Silk Scarf',
    'transaction_id': 1093926285,
    'transaction_type': 'listing',
    'url': 'https://www.etsy.com/transaction/1093926285',
    'variations': [{
        'formatted_name': 'Color',
        'formatted_value': 'Gray',
        'property_id': 200,
        'value_id': 1166197774}]
}, {
    'buyer_feedback_id': None,
    'buyer_user_id': 77713718,
    'creation_tsz': 1449600584,
    'currency_code': 'USD',
    'description': 'Nothing is for sale.  Testing only.',
    'file_data': u'',
    'image_listing_id': 885181915,
    'is_digital': False,
    'is_quick_sale': False,
    'listing_id': 259743529,
    'materials': [],
    'paid_tsz': 1449600660,
    'price': '0.30',
    'quantity': 1,
    'receipt_id': 1062792031,
    'seller_feedback_id': None,
    'seller_user_id': 28651835,
    'shipped_tsz': None,
    'shipping_cost': '0.00',
    'tags': ['Accessories', 'Scarf', 'testingonly', 'notforsale'],
    'title': 'Silk Scarf Clasp',
    'transaction_id': 1091015822,
    'transaction_type': 'listing',
    'url': 'https://www.etsy.com/transaction/1091015822',
    'variations': [{
        'formatted_name': 'Material',
        'formatted_value': 'Copper',
        'property_id': 507,
        'value_id': 2599060929
    }]
}]


RECEIPTS_RESPONSE = [{
    'adjusted_grandtotal': '1.90',
    'buyer_email': 'etsy@freshblend.com',
    'buyer_user_id': 77713718,
    'city': 'Brooklyn',
    'country_id': 209,
    'creation_tsz': 1449600584,
    'currency_code': 'USD',
    'discount_amt': '0.00',
    'first_line': '129 Clinton Ave',
    'grandtotal': '1.90',
    'has_local_delivery': False,
    'last_modified_tsz': 1453248217,
    'message_from_buyer': u'',
    'message_from_payment': None,
    'message_from_seller': 'This is for testing only.  Nothing is actually for sale',
    'name': 'Matt Laszuk',
    'order_id': 367750199,
    'payment_email': u'',
    'payment_method': 'other',
    'receipt_id': 1062792031,
    'receipt_type': 0,
    'second_line': u'',
    'seller_email': 'gen@freshblend.com',
    'seller_user_id': 28651835,
    'shipments': [],
    'shipping_carrier': None,
    'shipping_details': {
        'can_mark_as_shipped': True,
        'is_future_shipment': True,
        'not_shipped_state_display': 'Not Shipped',
        'shipping_method': 'Standard Shipping',
        'was_shipped': False
    },
    'shipping_note': None,
    'shipping_notification_date': None,
    'shipping_tracking_code': None,
    'shipping_tracking_url': None,
    'state': 'NY',
    'subtotal': '0.90',
    'total_price': '0.90',
    'total_shipping_cost': '1.00',
    'total_tax_cost': '0.00',
    'total_vat_cost': '0.00',
    'was_paid': True,
    'was_shipped': False,
    'zip': '11205'
}]
