PAYMENTS_RESPONSE = [{
    u'additive_tax': [],
    u'additive_tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'created_at': u'2015-11-18T19:30:50Z',
    u'creator_id': u'9J4BFEHCXZFAW',
    u'device': {u'id': u'DEVICE_INSTALLATION_ID:DE02BB16-D13B-4405-ACCB-AF91E9E3F3D6', u'name': u'Fresh Phone'},
    u'discount_money': {u'amount': 0, u'currency_code': u'USD'},
    u'gross_sales_money': {u'amount': 100, u'currency_code': u'USD'},
    u'id': u'fZR0ZGHuHjprkXOtojv5S',
    u'inclusive_tax': [],
    u'inclusive_tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'itemizations': [{
        u'discount_money': {u'amount': 0, u'currency_code': u'USD'},
        u'discounts': [],
        u'gross_sales_money': {u'amount': 100, u'currency_code': u'USD'},
        u'item_detail': {u'category_name': u'', u'sku': u''},
        u'itemization_type': u'CUSTOM_AMOUNT',
        u'modifiers': [],
        u'name': u'Custom Amount',
        u'net_sales_money': {u'amount': 100, u'currency_code': u'USD'},
        u'quantity': u'1.00000000',
        u'single_quantity_money': {u'amount': 100, u'currency_code': u'USD'},
        u'taxes': [],
        u'total_money': {u'amount': 100, u'currency_code': u'USD'}
    }],
    u'merchant_id': u'9J4BFEHCXZFAW',
    u'net_sales_money': {u'amount': 100, u'currency_code': u'USD'},
    u'net_total_money': {u'amount': 100, u'currency_code': u'USD'},
    u'payment_url': u'https://squareup.com/dashboard/sales/transactions/NyEdD7TB7lKUwZQuN3Z6gtMF',
    u'processing_fee_money': {u'amount': 0, u'currency_code': u'USD'},
    u'receipt_url': u'https://squareup.com/receipt/preview/fZR0ZGHuHjprkXOtojv5S',
    u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
    u'refunds': [],
    u'swedish_rounding_money': {u'amount': 0, u'currency_code': u'USD'},
    u'tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'tender': [{
        u'change_back_money': {u'amount': 0, u'currency_code': u'USD'},
        u'id': u'fZR0ZGHuHjprkXOtojv5S',
        u'name': u'Cash',
        u'receipt_url': u'https://squareup.com/receipt/preview/fZR0ZGHuHjprkXOtojv5S',
        u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
        u'tendered_money': {u'amount': 100, u'currency_code': u'USD'},
        u'total_money': {u'amount': 100, u'currency_code': u'USD'},
        u'type': u'CASH'
    }],
    u'tip_money': {u'amount': 0, u'currency_code': u'USD'},
    u'total_collected_money': {u'amount': 100, u'currency_code': u'USD'}
}, {
    u'additive_tax': [],
    u'additive_tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'created_at': u'2015-11-18T22:14:02Z',
    u'creator_id': u'9J4BFEHCXZFAW',
    u'device': {u'id': u'DEVICE_INSTALLATION_ID:DE02BB16-D13B-4405-ACCB-AF91E9E3F3D6', u'name': u'Fresh Phone'},
    u'discount_money': {u'amount': 0, u'currency_code': u'USD'},
    u'gross_sales_money': {u'amount': 100, u'currency_code': u'USD'},
    u'id': u'09Hj0HwcoiUXpQnqUzR2HwMF',
    u'inclusive_tax': [],
    u'inclusive_tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'itemizations': [{
        u'discount_money': {u'amount': 0, u'currency_code': u'USD'},
        u'discounts': [],
        u'gross_sales_money': {u'amount': 100, u'currency_code': u'USD'},
        u'item_detail': {u'category_name': u'', u'sku': u''},
        u'itemization_type': u'CUSTOM_AMOUNT',
        u'modifiers': [],
        u'name': u'Custom Amount',
        u'net_sales_money': {u'amount': 100, u'currency_code': u'USD'},
        u'quantity': u'1.00000000',
        u'single_quantity_money': {u'amount': 100, u'currency_code': u'USD'},
        u'taxes': [],
        u'total_money': {u'amount': 100, u'currency_code': u'USD'}
    }],
    u'merchant_id': u'9J4BFEHCXZFAW',
    u'net_sales_money': {u'amount': 100, u'currency_code': u'USD'},
    u'net_total_money': {u'amount': 81, u'currency_code': u'USD'},
    u'payment_url': u'https://squareup.com/dashboard/sales/transactions/br5dQjVQUL9X8Z0BxIeqhwMF',
    u'processing_fee_money': {u'amount': -19, u'currency_code': u'USD'},
    u'receipt_url': u'https://squareup.com/receipt/preview/09Hj0HwcoiUXpQnqUzR2HwMF',
    u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
    u'refunds': [],
    u'swedish_rounding_money': {u'amount': 0, u'currency_code': u'USD'},
    u'tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'tender': [{
        u'card_brand': u'MASTER_CARD',
        u'entry_method': u'MANUAL',
        u'id': u'09Hj0HwcoiUXpQnqUzR2HwMF',
        u'name': u'Credit Card',
        u'pan_suffix': u'2604',
        u'receipt_url': u'https://squareup.com/receipt/preview/09Hj0HwcoiUXpQnqUzR2HwMF',
        u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
        u'total_money': {u'amount': 100, u'currency_code': u'USD'},
        u'type': u'CREDIT_CARD'
    }],
    u'tip_money': {u'amount': 0, u'currency_code': u'USD'},
    u'total_collected_money': {u'amount': 100, u'currency_code': u'USD'}
}, {
    u'additive_tax': [{
        u'applied_money': {u'amount': 153, u'currency_code': u'USD'},
        u'fee_id': u'a9d56f34-d5d6-4017-bcc9-314287414639',
        u'inclusion_type': u'ADDITIVE',
        u'name': u'NY Clothing Tax',
        u'rate': u'0.08875000'
    }],
    u'additive_tax_money': {u'amount': 153, u'currency_code': u'USD'},
    u'created_at': u'2015-11-19T20:18:43Z',
    u'creator_id': u'9J4BFEHCXZFAW',
    u'device': {u'id': u'DEVICE_INSTALLATION_ID:DE02BB16-D13B-4405-ACCB-AF91E9E3F3D6', u'name': u'Fresh Phone'},
    u'discount_money': {u'amount': -575, u'currency_code': u'USD'},
    u'gross_sales_money': {u'amount': 2300, u'currency_code': u'USD'},
    u'id': u'ZKTkVt44oY53AYZlq98bStMF',
    u'inclusive_tax': [],
    u'inclusive_tax_money': {u'amount': 0, u'currency_code': u'USD'},
    u'itemizations': [{
        u'discount_money': {u'amount': -250, u'currency_code': u'USD'},
        u'discounts': [{
            u'applied_money': {u'amount': -250, u'currency_code': u'USD'},
            u'discount_id': u'81c0a84f-aac5-4389-8918-50700ac50064',
            u'name': u'End of Season Sale'
        }],
        u'gross_sales_money': {u'amount': 1000, u'currency_code': u'USD'},
        u'item_detail': {
            u'category_name': u'Scarves',
            u'item_id': u'bdd1230e-6987-44ea-b99d-d48862e3313d',
            u'item_variation_id': u'5bef38a0-78ab-4b15-9e37-4246a262a7e0',
            u'sku': u'000000000001'
        },
        u'item_variation_name': u'Regular',
        u'itemization_type': u'ITEM',
        u'modifiers': [],
        u'name': u'Silk Scarf',
        u'net_sales_money': {u'amount': 750, u'currency_code': u'USD'},
        u'notes': u'The first scarf you should buy',
        u'quantity': u'1.00000000',
        u'single_quantity_money': {u'amount': 1000, u'currency_code': u'USD'},
        u'taxes': [{
            u'applied_money': {u'amount': 67, u'currency_code': u'USD'},
            u'fee_id': u'a9d56f34-d5d6-4017-bcc9-314287414639',
            u'inclusion_type': u'ADDITIVE',
            u'name': u'NY Clothing Tax',
            u'rate': u'0.08875000'
        }],
        u'total_money': {u'amount': 817, u'currency_code': u'USD'}
    }, {
        u'discount_money': {u'amount': -25, u'currency_code': u'USD'},
        u'discounts': [{
            u'applied_money': {u'amount': -25, u'currency_code': u'USD'},
            u'discount_id': u'81c0a84f-aac5-4389-8918-50700ac50064',
            u'name': u'End of Season Sale'
        }],
        u'gross_sales_money': {u'amount': 100, u'currency_code': u'USD'},
        u'item_detail': {
            u'category_name': u'Scarf Accessories',
            u'item_id': u'bc88b3c9-633a-4d45-84bd-6b681f09ce84',
            u'item_variation_id': u'cfde557d-c21c-43e2-9f89-68b77c230103',
            u'sku': u'000000000003'
        },
        u'item_variation_name': u'Regular',
        u'itemization_type': u'ITEM',
        u'modifiers': [],
        u'name': u'Silk Scarf Clasp',
        u'net_sales_money': {u'amount': 75, u'currency_code': u'USD'},
        u'quantity': u'1.00000000',
        u'single_quantity_money': {u'amount': 100, u'currency_code': u'USD'},
        u'taxes': [{
            u'applied_money': {u'amount': 7, u'currency_code': u'USD'},
            u'fee_id': u'a9d56f34-d5d6-4017-bcc9-314287414639',
            u'inclusion_type': u'ADDITIVE',
            u'name': u'NY Clothing Tax',
            u'rate': u'0.08875000'
        }],
        u'total_money': {u'amount': 82, u'currency_code': u'USD'}
    }, {
        u'discount_money': {u'amount': -300, u'currency_code': u'USD'},
        u'discounts': [{
            u'applied_money': {u'amount': -300, u'currency_code': u'USD'},
            u'discount_id': u'81c0a84f-aac5-4389-8918-50700ac50064',
            u'name': u'End of Season Sale'
        }],
        u'gross_sales_money': {u'amount': 1200, u'currency_code': u'USD'},
        u'item_detail': {
            u'category_name': u'Scarves',
            u'item_id': u'21e888aa-c902-4ffb-a704-ca00011386d4',
            u'item_variation_id': u'af4332dc-5acd-4cdb-a4d8-cc3cdab869a4',
            u'sku': u'000000000002'
        },
        u'item_variation_name': u'Regular',
        u'itemization_type': u'ITEM',
        u'modifiers': [],
        u'name': u'Two-tone Scarf',
        u'net_sales_money': {u'amount': 900, u'currency_code': u'USD'},
        u'notes': u'A fancy scarf for fancy occasions',
        u'quantity': u'1.00000000',
        u'single_quantity_money': {u'amount': 1200, u'currency_code': u'USD'},
        u'taxes': [{
            u'applied_money': {u'amount': 79, u'currency_code': u'USD'},
            u'fee_id': u'a9d56f34-d5d6-4017-bcc9-314287414639',
            u'inclusion_type': u'ADDITIVE',
            u'name': u'NY Clothing Tax',
            u'rate': u'0.08875000'
        }],
        u'total_money': {u'amount': 979, u'currency_code': u'USD'}
    }],
    u'merchant_id': u'9J4BFEHCXZFAW',
    u'net_sales_money': {u'amount': 1725, u'currency_code': u'USD'},
    u'net_total_money': {u'amount': 1878, u'currency_code': u'USD'},
    u'payment_url': u'https://squareup.com/dashboard/sales/transactions/ZKTkVt44oY53AYZlq98bStMF',
    u'processing_fee_money': {u'amount': 0, u'currency_code': u'USD'},
    u'receipt_url': u'https://squareup.com/receipt/preview/bF0a1iEkxDV8Bon2byy5S',
    u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
    u'refunds': [],
    u'swedish_rounding_money': {u'amount': 0, u'currency_code': u'USD'},
    u'tax_money': {u'amount': 153, u'currency_code': u'USD'},
    u'tender': [{
        u'id': u'bF0a1iEkxDV8Bon2byy5S',
        u'name': u'CHECK',
        u'receipt_url': u'https://squareup.com/receipt/preview/bF0a1iEkxDV8Bon2byy5S',
        u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
        u'total_money': {u'amount': 878, u'currency_code': u'USD'},
        u'type': u'OTHER'
    }, {
        u'change_back_money': {u'amount': 0, u'currency_code': u'USD'},
        u'id': u'btOVD1JUNTWwp92L7qx5S',
        u'name': u'Cash',
        u'receipt_url': u'https://squareup.com/receipt/preview/btOVD1JUNTWwp92L7qx5S',
        u'refunded_money': {u'amount': 0, u'currency_code': u'USD'},
        u'tendered_money': {u'amount': 1000, u'currency_code': u'USD'},
        u'total_money': {u'amount': 1000, u'currency_code': u'USD'},
        u'type': u'CASH'
    }],
    u'tip_money': {u'amount': 0, u'currency_code': u'USD'},
    u'total_collected_money': {u'amount': 1878, u'currency_code': u'USD'}
}]
